theme: jekyll-theme-minimal
title: GitHub pages template
description: My webpage
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: qim shi xiao gougou
    url: test.html
